### ISSUE TITLE
Bulleted lists have different sizing and font, and possible indentation problem

### ISSUE THREAD

**Issue by EdualcLaiv** [SMUsamaShah/Obsidian-Win98-Edition#1]
Hello,

- In preview mode, lists are not resized  (when changing font size (in settings or with ctrl/cmd + mouse wheel).
- It aslo seems they use a different font.
- I might be wrong but the way lists are indented seems off in preview mode. (it's more visible with small font size)

Min font size:
![image](https://user-images.githubusercontent.com/4270058/131033420-3dd92a8c-9999-41f3-a0ed-53a9ea6a66c5.png)

Max font size:
![image](https://user-images.githubusercontent.com/4270058/131033490-80bea7ca-22f6-4435-9864-5e64bf3a6238.png)

**Comment by SMUsamaShah** [comment]
Hi, This is a mistake on my part. The lists or anything else in the document is not supposed to change at all with the theme. It's only meant to change the UI of Obsidian.

**Comment by SMUsamaShah** [comment]
Fixed
