### ISSUE TITLE
Checkboxes aren't visible in preview mode

### ISSUE THREAD

**Issue by andrew-1234** [SMUsamaShah/Obsidian-Win98-Edition#2]
Hi, I love this theme but I can't see any checkboxes ( - [ ] ) rendered in the visual preview mode. 
Thanks.

**Comment by SMUsamaShah** [comment]
Thanks for reporting. Fixed it. I don't know how long it takes the changes to reflect in community themes. You can meanwhile download the .css file yourself from this repo.
