### ISSUE TITLE
Shimmy title bar text over on Mac OS?

### ISSUE THREAD

**Issue by ryanpcmcquen** [SMUsamaShah/Obsidian-Win98-Edition#4]
Thank you so much for this fantastic theme. I love how it looks, and appreciate all the effort that went into this.

Is there a way to shimmy the title text over on Mac OS so that it isn't overlaid with the Minimize/Zoom/Close buttons?

<img width="201" alt="Screen Shot 2021-12-09 at 12 45 19 PM" src="https://user-images.githubusercontent.com/772937/145473084-1821a436-f9d1-4e81-bb27-40bb2f207b4e.png">

**Comment by ryanpcmcquen** [comment]
For now I've added a CSS snippet as a workaround:
```css
.titlebar-text {
    margin-left: 75px;
}
```

**Comment by SMUsamaShah** [comment]
Can we check in CSS if it's Mac? float: left might work but I am not sure. 

Please share html that renders titlebar on Mac.

Setting margins hard-coded would break it on Windows etc

**Comment by ryanpcmcquen** [comment]
I think there are platform specific classes, I'll do some digging here, since that would be a nice fix for everyone.

**Comment by ryanpcmcquen** [comment]
`float: left;` did not work, but this does:

```
.mod-macos .titlebar-text {
    margin-left: 75px;
}
```

**Comment by SMUsamaShah** [comment]
Updated the css with your fix. Thanks :)
